name: NASA Project CI (custom)
on: # triggers on these 2 events
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js version 16
      - uses: actions/checkout@v2 # using Github Actions
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm build --prefix client
