name: NASA Project CI (custom)
on: # triggers on these 2 events
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true # disables watch-mode automatically
      MONGO_URL: mongodb://localhost/nasa # point to db
    strategy:
      matrix: # Run all the steps 2 times (for the following node-versions)
        node-version: [14.x, 16.x]
        mongodb-version: ["4.4"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # using Github Actions
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB in GitHub Action
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
